### ISSUE TITLE
Feature: Manual configuration

### ISSUE THREAD

**Issue by iamssen** [rocket-hangar/jest-bin#2]
```yaml
'packages/package-a/*':
  bin: ./node_modules/.bin/react-app-rewired
  root: packages/package-a
'apps/(app-a|app-b)/*':
  bin: ./node_modules/.bin/react-scripts
  root: apps/$1
default:
  bin: ./node_modules/.bin/jest
```
